import RealityKit
import simd
import UIKit

// MARK: - PinballEntities

struct PinballEntities {
    let root         : Entity
    let ball         : Entity
    let leftFlipper  : Entity
    let rightFlipper : Entity
}

// MARK: - PinballTableBuilder
// Models are generated by BlenderModels/generate_pinball_models.py and
// bundled as .usdz files in the app target.

enum PinballTableBuilder {

    // MARK: - Dimensions (kept for collision shapes – match Blender export sizes)
    private static let tableW   : Float = 0.44
    private static let tableH   : Float = 1.00
    private static let wallT    : Float = 0.014
    private static let ballR    : Float = 0.023
    private static let flipLen  : Float = 0.16
    private static let flipH    : Float = 0.020
    private static let flipD    : Float = 0.052
    private static let bumperR  : Float = 0.032
    private static let bumperH  : Float = 0.058

    private static let quatID = simd_quatf(ix: 0, iy: 0, iz: 0, r: 1)

    // Neon palette (for point lights – the mesh colours come from Blender materials)
    private static let neonLightColors: [UIColor] = [
        UIColor(red: 0.0, green: 1.0, blue: 1.0, alpha: 1),   // cyan
        UIColor(red: 1.0, green: 0.1, blue: 0.9, alpha: 1),   // magenta
        UIColor(red: 1.0, green: 0.9, blue: 0.0, alpha: 1),   // yellow
        UIColor(red: 0.2, green: 1.0, blue: 0.4, alpha: 1),   // green
        UIColor(red: 1.0, green: 0.35, blue: 0.0, alpha: 1),  // orange
    ]

    // MARK: - Build

    static func build() -> PinballEntities {
        let root = Entity()
        root.name = "PinballTable"

        buildTableBody(in: root)
        buildSlingshots(in: root)
        buildDiagonalGuards(in: root)
        buildGutter(in: root)
        buildRolloverLanes(in: root)
        buildBumpers(in: root)
        buildLaneLights(in: root)

        let left  = makeFlipper(side: -1)
        let right = makeFlipper(side:  1)
        left.transform.rotation  = simd_quatf(angle: -.pi / 7.2, axis: [0, 0, 1])
        right.transform.rotation = simd_quatf(angle:  .pi / 7.2, axis: [0, 0, 1])
        root.addChild(left)
        root.addChild(right)

        let ball = makeBall()
        ball.position = SIMD3(0, -0.12, 0)
        root.addChild(ball)

        return PinballEntities(root: root, ball: ball,
                               leftFlipper: left, rightFlipper: right)
    }

    // MARK: - Table Body (procedural — always visible in passthrough)

    private static func buildTableBody(in root: Entity) {
        // The Blender USDZ uses PBR dark/chrome materials (near-black matte surface,
        // mirror chrome walls) that appear nearly invisible in visionOS passthrough
        // without strong image-based lighting. Procedural UnlitMaterial geometry
        // renders at exactly its specified color regardless of scene lighting.
        buildFallbackTableBody(in: root)
    }

    private static func buildFallbackTableBody(in root: Entity) {
        let depth: Float = 0.13
        let halfD: Float = depth / 2

        // ── Back panel — deep indigo, clearly darker than any room wall ────
        let panelMat = UnlitMaterial(color: UIColor(red: 0.04, green: 0.03, blue: 0.18, alpha: 1))
        let panel    = ModelEntity(
            mesh: MeshResource.generateBox(size: SIMD3(tableW + wallT * 2, tableH + wallT * 2, 0.008)),
            materials: [panelMat])
        panel.position = SIMD3(0, 0, -halfD + 0.004)
        root.addChild(panel)

        // ── Play-field surface — slightly lighter so the active area reads ─
        let fieldMat = UnlitMaterial(color: UIColor(red: 0.06, green: 0.05, blue: 0.24, alpha: 1))
        let field    = ModelEntity(
            mesh: MeshResource.generateBox(size: SIMD3(tableW, tableH, 0.003)),
            materials: [fieldMat])
        field.position = SIMD3(0, 0, -halfD + 0.014)
        root.addChild(field)

        // ── Neon border — drawn on the FRONT face so it catches the eye ───
        let neonMat  = UnlitMaterial(color: UIColor(red: 0.0, green: 1.0, blue: 1.0, alpha: 1))
        let bW: Float = 0.010
        let hw        = tableW / 2 + wallT
        let hh        = tableH / 2 + wallT

        // Front-face neon frame
        let fz: Float = halfD - 0.003
        let frontEdges: [(SIMD3<Float>, SIMD3<Float>)] = [
            (SIMD3(-hw,  0, fz), SIMD3(bW, tableH + wallT * 2 + bW * 2, bW)),
            (SIMD3( hw,  0, fz), SIMD3(bW, tableH + wallT * 2 + bW * 2, bW)),
            (SIMD3( 0,  hh, fz), SIMD3(tableW + wallT * 2 + bW * 2, bW, bW)),
            (SIMD3( 0, -hh, fz), SIMD3(tableW + wallT * 2 + bW * 2, bW, bW)),
        ]
        // Back-face neon frame (gives cabinet depth)
        let bz: Float = -halfD + 0.012
        let backEdges: [(SIMD3<Float>, SIMD3<Float>)] = [
            (SIMD3(-hw,  0, bz), SIMD3(bW, tableH + wallT * 2 + bW * 2, bW)),
            (SIMD3( hw,  0, bz), SIMD3(bW, tableH + wallT * 2 + bW * 2, bW)),
            (SIMD3( 0,  hh, bz), SIMD3(tableW + wallT * 2 + bW * 2, bW, bW)),
            (SIMD3( 0, -hh, bz), SIMD3(tableW + wallT * 2 + bW * 2, bW, bW)),
        ]
        for (pos, size) in frontEdges + backEdges {
            let e = ModelEntity(mesh: MeshResource.generateBox(size: size), materials: [neonMat])
            e.position = pos
            root.addChild(e)
        }

        // ── Side walls — dark with collision physics ───────────────────────
        let wallMat = UnlitMaterial(color: UIColor(red: 0.10, green: 0.10, blue: 0.16, alpha: 1))
        let wallVis: Float = 0.022

        addUnlitBox(root, pos: SIMD3(-(tableW / 2 + wallVis / 2),  0,  0),
                    size: SIMD3(wallVis, tableH + wallVis * 2, depth),
                    mat: wallMat, name: "wallLeft")
        addUnlitBox(root, pos: SIMD3(  tableW / 2 + wallVis / 2,  0,  0),
                    size: SIMD3(wallVis, tableH + wallVis * 2, depth),
                    mat: wallMat, name: "wallRight")
        addUnlitBox(root, pos: SIMD3(0,  tableH / 2 + wallVis / 2, 0),
                    size: SIMD3(tableW + wallVis * 2, wallVis, depth),
                    mat: wallMat, name: "wallTop")

        // ── Scene fill lights — illuminate the chrome PBR models ──────────
        // (bumpers have self-emission; flippers, guards, and ball need lighting)
        let sceneLights: [(SIMD3<Float>, UIColor, Float)] = [
            (SIMD3( 0.00,  0.25,  0.10), UIColor(red: 0.7, green: 0.85, blue: 1.0, alpha: 1), 4500),
            (SIMD3( 0.00, -0.20,  0.10), UIColor(red: 0.8, green: 0.65, blue: 1.0, alpha: 1), 2800),
            (SIMD3( 0.00,  0.00,  0.12), UIColor(red: 1.0, green: 0.95, blue: 0.85, alpha: 1), 1800),
        ]
        for (pos, color, intensity) in sceneLights {
            var lc = PointLightComponent()
            lc.color             = color
            lc.intensity         = intensity
            lc.attenuationRadius = 1.0
            let le = Entity(); le.position = pos; le.components.set(lc)
            root.addChild(le)
        }
    }

    // MARK: - Slingshots
    // Magenta kicker wedges on both sides of the lower table.
    // Physics: static bodies with high restitution (1.3) so they kick the ball
    // toward the centre when hit. Named "slingshot_0" / "slingshot_1" so the
    // collision handler can detect and score them.

    private static func buildSlingshots(in root: Entity) {
        let slingSz  = SIMD3<Float>(0.09, wallT, 0.055)
        let slingCol = UIColor(red: 1.0, green: 0.1, blue: 0.85, alpha: 1)  // magenta

        for (i, side) in [Float(-1), Float(1)].enumerated() {
            let sling = Entity()
            sling.name = "slingshot_\(i)"
            sling.position = SIMD3(side * 0.185, -0.14, 0)
            // Angle inward so the ball deflects toward centre-top
            sling.transform.rotation = simd_quatf(angle: side * .pi / 5.5, axis: [0, 0, 1])

            // Visual — bright magenta unlit bar
            let mat = UnlitMaterial(color: slingCol)
            let vis = ModelEntity(mesh: MeshResource.generateBox(size: slingSz), materials: [mat])
            sling.addChild(vis)

            // Physics
            let shape = ShapeResource.generateBox(size: slingSz)
            sling.components.set(CollisionComponent(shapes: [shape]))
            var body = PhysicsBodyComponent()
            body.mode     = .static
            body.material = .generate(friction: 0.05, restitution: 1.30)
            sling.components.set(body)

            // Magenta point light
            var light = PointLightComponent()
            light.color             = slingCol
            light.intensity         = 2800
            light.attenuationRadius = 0.20
            sling.components.set(light)

            root.addChild(sling)
        }
    }

    // MARK: - Rollover Lanes
    // Three invisible trigger strips across the table width.
    // Named "lane_0..2" — scored in handleCollision without physics interaction.
    // A thin neon line marks each strip visually.

    private static func buildRolloverLanes(in root: Entity) {
        let laneYs   : [Float]   = [0.38, -0.05, -0.24]
        let laneColors: [UIColor] = [
            UIColor(red: 1.0, green: 0.9, blue: 0.0, alpha: 1),  // yellow
            UIColor(red: 0.2, green: 1.0, blue: 0.5, alpha: 1),  // green
            UIColor(red: 0.4, green: 0.7, blue: 1.0, alpha: 1),  // blue
        ]
        let stripW: Float = tableW - 0.05

        for (i, y) in laneYs.enumerated() {
            let lane = Entity()
            lane.name = "lane_\(i)"
            lane.position = SIMD3(0, y, 0)

            // Trigger — no PhysicsBodyComponent, just a collision sensor
            var col = CollisionComponent(
                shapes: [ShapeResource.generateBox(size: SIMD3(stripW, 0.018, 0.10))])
            col.mode = .trigger
            lane.components.set(col)

            // Thin neon line so the player can see where the lanes are
            let lineMat = UnlitMaterial(color: laneColors[i])
            let line    = ModelEntity(
                mesh: MeshResource.generateBox(size: SIMD3(stripW, 0.002, 0.003)),
                materials: [lineMat])
            lane.addChild(line)

            // Subtle glow
            var glow = PointLightComponent()
            glow.color             = laneColors[i]
            glow.intensity         = 500
            glow.attenuationRadius = 0.18
            lane.components.set(glow)

            root.addChild(lane)
        }
    }

    // MARK: - Diagonal Guards (Blender USDZ)

    private static func buildDiagonalGuards(in root: Entity) {
        for side: Float in [-1, 1] {
            let guardEntity = Entity()
            guardEntity.name = "guard_\(side)"
            guardEntity.position = SIMD3(side * 0.165, -0.355, 0)
            guardEntity.transform.rotation = simd_quatf(angle: side * .pi / 4, axis: [0, 0, 1])

            if let model = try? ModelEntity.loadModel(named: "pinball_diagonal_guard") {
                guardEntity.addChild(model)
            } else {
                // Fallback procedural guard
                var mat = PhysicallyBasedMaterial()
                mat.baseColor = .init(tint: UIColor(white: 0.7, alpha: 1))
                mat.metallic  = .init(floatLiteral: 0.8)
                mat.roughness = .init(floatLiteral: 0.2)
                let size  = SIMD3<Float>(0.13, wallT, 0.065)
                let visual = ModelEntity(mesh: MeshResource.generateBox(size: size), materials: [mat])
                guardEntity.addChild(visual)
            }

            let size  = SIMD3<Float>(0.13, wallT, 0.065)
            let shape = ShapeResource.generateBox(size: size)
            guardEntity.components.set(CollisionComponent(shapes: [shape]))
            var body = PhysicsBodyComponent(); body.mode = .static
            body.material = .generate(friction: 0.1, restitution: 0.62)
            guardEntity.components.set(body)

            root.addChild(guardEntity)
        }
    }

    // MARK: - Gutter trigger

    private static func buildGutter(in root: Entity) {
        let g = Entity(); g.name = "gutter"
        g.position = SIMD3(0, -(tableH/2 + wallT * 2), 0)
        var col = CollisionComponent(
            shapes: [ShapeResource.generateBox(size: SIMD3(tableW, wallT, 0.13))])
        col.mode = .trigger
        g.components.set(col)
        root.addChild(g)
    }

    // MARK: - Neon Bumpers (Blender USDZ)

    private static func buildBumpers(in root: Entity) {
        let positions: [SIMD3<Float>] = [
            SIMD3(-0.10,  0.20, 0),
            SIMD3( 0.10,  0.20, 0),
            SIMD3( 0.00,  0.32, 0),
            SIMD3(-0.14,  0.06, 0),
            SIMD3( 0.14,  0.06, 0),
        ]
        for (i, pos) in positions.enumerated() {
            addNeonBumper(root, position: pos, colorIndex: i)
        }
    }

    private static func addNeonBumper(_ root: Entity,
                                      position: SIMD3<Float>,
                                      colorIndex: Int) {
        let bumper = Entity()
        bumper.name = "bumper_\(colorIndex)"
        bumper.position = position

        // Physics
        let shape = ShapeResource.generateCapsule(height: bumperH, radius: bumperR)
        bumper.components.set(CollisionComponent(shapes: [shape]))
        var body = PhysicsBodyComponent()
        body.mode     = .static
        body.material = .generate(friction: 0.05, restitution: 1.45)
        bumper.components.set(body)

        // Blender USDZ visual (tinted per bumper slot via point light color)
        if let model = try? ModelEntity.loadModel(named: "pinball_bumper") {
            bumper.addChild(model)
        } else {
            // Fallback neon cylinder
            let color   = neonLightColors[colorIndex % neonLightColors.count]
            let coreMat = UnlitMaterial(color: color)
            let core    = ModelEntity(
                mesh: MeshResource.generateCylinder(height: bumperH, radius: bumperR),
                materials: [coreMat])
            bumper.addChild(core)
        }

        // Point light for scene glow (color varies per bumper)
        var light = PointLightComponent()
        light.color             = neonLightColors[colorIndex % neonLightColors.count]
        light.intensity         = 4500
        light.attenuationRadius = 0.22
        bumper.components.set(light)

        root.addChild(bumper)
    }

    // MARK: - Lane Lights (Blender USDZ)

    private static func buildLaneLights(in root: Entity) {
        let ySteps: [Float] = [-0.3, -0.15, 0, 0.15, 0.3, 0.42]
        for y in ySteps {
            for x: Float in [-(tableW/2 - 0.01), (tableW/2 - 0.01)] {
                let dot = Entity()
                dot.position = SIMD3(x, y, -0.04)

                var light = PointLightComponent()
                light.color             = UIColor(red: 0.4, green: 0.6, blue: 1.0, alpha: 1)
                light.intensity         = 300
                light.attenuationRadius = 0.08
                dot.components.set(light)

                if let led = try? ModelEntity.loadModel(named: "pinball_lane_led") {
                    dot.addChild(led)
                } else {
                    let disc = ModelEntity(
                        mesh: MeshResource.generateCylinder(height: 0.002, radius: 0.005),
                        materials: [UnlitMaterial(
                            color: UIColor(red: 0.4, green: 0.6, blue: 1, alpha: 1))])
                    disc.transform.rotation = simd_quatf(angle: .pi/2, axis: [1, 0, 0])
                    dot.addChild(disc)
                }

                root.addChild(dot)
            }
        }
    }

    // MARK: - Flippers (Blender USDZ)

    private static func makeFlipper(side: Float) -> Entity {
        let pivot = Entity()
        pivot.name = side < 0 ? "flipperLeft" : "flipperRight"
        pivot.position = SIMD3(side * 0.10, -0.42, 0)

        let offsetX = side * flipLen / 2
        let shape   = ShapeResource.generateBox(size: SIMD3(flipLen, flipH, flipD))
            .offsetBy(rotation: quatID, translation: SIMD3(-offsetX, 0, 0))
        pivot.components.set(CollisionComponent(shapes: [shape]))
        var body = PhysicsBodyComponent()
        body.mode     = .kinematic
        body.material = .generate(friction: 0.25, restitution: 0.68)
        pivot.components.set(body)

        if let model = try? ModelEntity.loadModel(named: "pinball_flipper") {
            // Mirror right flipper on X axis
            if side > 0 { model.scale.x = -1 }
            model.position = SIMD3(-offsetX, 0, 0)
            pivot.addChild(model)
        } else {
            // Fallback chrome box
            var mat = PhysicallyBasedMaterial()
            mat.baseColor = .init(tint: UIColor(white: 0.95, alpha: 1))
            mat.metallic  = .init(floatLiteral: 0.92)
            mat.roughness = .init(floatLiteral: 0.10)
            let visual = ModelEntity(
                mesh: MeshResource.generateBox(size: SIMD3(flipLen, flipH, flipD)),
                materials: [mat])
            visual.position = SIMD3(-offsetX, 0, 0)
            pivot.addChild(visual)
        }

        // Neon edge light
        var edgeLight = PointLightComponent()
        edgeLight.color             = UIColor(red: 0.4, green: 0.8, blue: 1.0, alpha: 1)
        edgeLight.intensity         = 800
        edgeLight.attenuationRadius = 0.12
        let lightE = Entity()
        lightE.position = SIMD3(-offsetX, 0, 0.03)
        lightE.components.set(edgeLight)
        pivot.addChild(lightE)

        return pivot
    }

    // MARK: - Ball (Blender USDZ)

    private static func makeBall() -> Entity {
        if let ball = try? ModelEntity.loadModel(named: "pinball_ball") {
            ball.name = "ball"
            let shape = ShapeResource.generateSphere(radius: ballR)
            ball.components.set(CollisionComponent(shapes: [shape]))
            var body = PhysicsBodyComponent()
            body.mode                = .dynamic
            body.material            = .generate(friction: 0.22, restitution: 0.58)
            body.massProperties.mass = 0.08
            body.isTranslationLocked = (x: false, y: false, z: true)
            body.isRotationLocked    = (x: true,  y: true,  z: false)
            body.linearDamping       = 0.04
            body.angularDamping      = 0.08
            ball.components.set(body)
            return ball
        }

        // Fallback mirror chrome sphere
        var mat = PhysicallyBasedMaterial()
        mat.baseColor = .init(tint: UIColor(white: 1.0, alpha: 1))
        mat.metallic  = .init(floatLiteral: 1.0)
        mat.roughness = .init(floatLiteral: 0.04)
        let ball  = ModelEntity(mesh: MeshResource.generateSphere(radius: ballR),
                                materials: [mat])
        ball.name = "ball"
        let shape = ShapeResource.generateSphere(radius: ballR)
        ball.components.set(CollisionComponent(shapes: [shape]))
        var body = PhysicsBodyComponent()
        body.mode                = .dynamic
        body.material            = .generate(friction: 0.22, restitution: 0.58)
        body.massProperties.mass = 0.08
        body.isTranslationLocked = (x: false, y: false, z: true)
        body.isRotationLocked    = (x: true,  y: true,  z: false)
        body.linearDamping       = 0.055
        body.angularDamping      = 0.12
        ball.components.set(body)
        return ball
    }

    // MARK: - Helpers

    // Unlit walls — visible regardless of scene lighting
    private static func addUnlitBox(_ root: Entity,
                                    pos: SIMD3<Float>,
                                    size: SIMD3<Float>,
                                    mat: UnlitMaterial,
                                    name: String) {
        let e = ModelEntity(mesh: MeshResource.generateBox(size: size), materials: [mat])
        e.name     = name
        e.position = pos
        let shape  = ShapeResource.generateBox(size: size)
        e.components.set(CollisionComponent(shapes: [shape]))
        var body = PhysicsBodyComponent()
        body.mode     = .static
        body.material = .generate(friction: 0.3, restitution: 0.5)
        e.components.set(body)
        root.addChild(e)
    }
}
